# Generated by Django 3.1.3 on 2020-11-23 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_new_model_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='user',
            new_name='author',
        ),
    ]
