# Generated by Django 3.1.3 on 2020-11-23 02:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_timestamp_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='new',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
