# Generated by Django 3.1.3 on 2020-11-23 02:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_add_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='publication',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='new',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='new',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='new',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
