# Generated by Django 3.1.3 on 2020-11-23 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_add_title_slug_status_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['-publication']},
        ),
    ]
