# Generated by Django 3.1.3 on 2020-11-23 02:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_ordering_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
