# Generated by Django 3.1.3 on 2020-12-13 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_add_news_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.section'),
        ),
    ]
