# Generated by Django 3.1.3 on 2020-12-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_add_news_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='color',
            field=models.CharField(choices=[('warning', 'Warning'), ('danger', 'Danger'), ('info', 'Info'), ('success', 'Success'), ('link', 'Link'), ('primary', 'Primary')], default='info', max_length=20),
        ),
    ]
