# Generated by Django 3.1.3 on 2020-12-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_add_news_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='youtube_video',
            field=models.URLField(blank=True),
        ),
    ]
