# Generated by Django 3.1.3 on 2020-12-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_add_resource_youtube_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='section',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
