# Generated by Django 3.1.5 on 2021-01-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_resource_image_blank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='youtube_video',
        ),
    ]
