# Generated by Django 3.1.5 on 2021-01-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_resource_delete_youtube_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
