name: 0 - Run Everything

on:
    workflow_dispatch:
    push:
        branches: [master]

jobs:
    test_django:
        uses: ./.github/workflows/test-django.yml
        secrets:
            DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
            DB_ENGINE: ${{ secrets.DB_ENGINE }}
            SERVER_DOMAIN: ${{ secrets.SERVER_DOMAIN }}
    build_django:
        needs: test_django
        uses: ./.github/workflows/container.yml