name: Give any name to your workflow

on:
  workflow_call:
    secrets:
      DJANGO_SECRET_KEY:
        required: true
      DB_ENGINE:
        required: true
      SERVER_DOMAIN:
        required: true
  workflow_dispatch:

jobs:
  test_django_project:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DB_ENGINE: ${{ secrets.DB_ENGINE }}
      SERVER_DOMAIN: ${{ secrets.SERVER_DOMAIN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Hello world
        run: |
          echo "DJANGO_SECRET_KEY: ${{ env.DJANGO_SECRET_KEY }}"
      - name: 'Create .env file'
        run: |
          cd webserver
          touch .env
          echo SECRET_KEY="${{ env.DJANGO_SECRET_KEY }}" >> .env
          echo DB_ENGINE=${{ env.DB_ENGINE }} >> .env
          echo SERVER_DOMAIN=${{ env.SERVER_DOMAIN }} >> .env
          cat .env
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python3.10 -m pip install -r requirements.txt
      - name: Run Tests
        run: |
          python ./webserver/manage.py test apps.news
          python ./webserver/manage.py test apps.social